# Streamlit Secrets Configuration
# This file should NEVER be committed to Git
# Add your API keys here

GEMINI_API_KEY = "AIzaSyBioseAlddVwbf-jiEiDHRJy1VPeXiqmmI"
SUPABASE_URL = "https://wuzhsricuvjgvtiiylhz.supabase.co"
SUPABASE_KEY = "sb_publishable_ZPld2JKhdzKJbw2N6CcQgw_1M4SAbu7"
